version: '3.9'

services:

  redis:
    platform: linux/amd64
    image: redis:6.2.6-alpine
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - postgres

  elasticsearch:
    platform: linux/amd64
    image: elasticsearch:7.16.3
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - postgres

  kibana:
    platform: linux/amd64
    image: kibana:7.16.3
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - postgres

  db:
    platform: linux/amd64
    build:
      context: .
      dockerfile: PostgresDockerfile
    container_name: postgresdb
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: nikhil
      POSTGRES_PASSWORD: nikhil
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - postgres

  pgadmin:
    platform: linux/amd64
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "nikhil@nikhil.com"
      PGADMIN_DEFAULT_PASSWORD: "nikhil"
    ports:
      - "5433:80"
    restart: unless-stopped
    networks:
      - postgres
    depends_on:
      - db

  pgsync:
    platform: linux/amd64
    build:
      context: .
      dockerfile: PgsyncDockerfile
    container_name: pgsync
    environment:
      - PG_USER=nikhil
      - PG_PASSWORD=nikhil
      - PG_HOST=db
      - ELASTICSEARCH_HOST=elasticsearch
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
      - elasticsearch
    networks:
      - postgres

volumes:
  elasticsearch-data:
    driver: local

networks:
  postgres:
    driver: bridge

# adminer:
# image: adminer
# restart: always
# ports:
# - 8080:8080
